print("Hello World!")
print("Hello again")
print("I like typing this.")
print("This is fun.")
print('Yay ! printing')
print("I'd rather you much you 'not'.")
print('I "said" do not touch this.')
